config/routes.rb
Rails.application.routes.draw do
  root to: "products#index"
  get '/products', action: :product, controller: 'products'
  get '/products/:id', action: :product_detail, controller: 'products', as: 'product'
  get '/catagory', action: :catagory, controller: 'products', as: 'catagory'
  get '/products', action: :search, controller: 'application'

  get '/orders/items', to:'orders#cart', as: 'orders'
  resources :orders, path: '/orders/items'
  

  get '/orders/checkout', to:'checkout#index', as: 'checkout'
  post '/orders/checkout', to:'checkout#create'

  devise_for :users
  
  get '/profile/new', to:'profiles#new'
  get '/profile/:id', to:'profiles#show'
  resources :profiles, path: '/profile'

  get '/signedinuserprofile' => 'profiles#signedinuserprofile'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/observer.rb
module Observer
	def initialize
		@observers=[]
	end

	def add_observer(observer)
		@observers << observer
	end

	def delete_observer(observer)
		@observers.delete(observer)
	end

	def notify_observers
		@observers.each do |observer|
			observer.update(self)
		end
	end
end

app/models/order.rb
class Order < ApplicationRecord
    
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :orders, optional: true

    def self.search(search)
        if search
            where(["name LIKE ?","%#(search)%"])
        else
            all
        end
    end
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
end

app/models/shopping_cart.rb
# https://github.com/BaylorRae/rails-shopping-cart/blob/master/app/models/shopping_cart.rb

require 'singleton'
require 'observer'

class ShoppingCart
    include Singleton
    include Observer

        def order
          Order.where(status: nil)
        end

        def items_count
          Order.where(status: nil).sum(:quantity)
        end
      
        def add_item(product_id:, user_id:, quantity: 1)
          product = Product.find(product_id)
          user = User.find(user_id)

          order = Order.find_or_initialize_by(product_id: product_id, user_id: user_id)
          

          order.price = product.Price
          order.quantity = quantity

          order.save
        end

        def observer(status: status, first_name: first_name, last_name: last_name)

          Order.where(status: nil).update(
              status: status,
              first_name: first_name,
              last_name: last_name
            )

          notify_observers
          puts "status: nil changes to #{status}"
        end
        
      def remove_item(id:)
        Order.destroy(id)
      end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  belongs_to :orders, optional: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
         has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :current_cart

  def current_cart
    @current_cart ||= ShoppingCart.instance
  end
  helper_method :current_cart

  def apis
    @call = HTTParty.get('https://api.exchangeratesapi.io/latest?symbols=USD,GBP', :verify => false)

    @rates = JSON.parse(@call.body)
    @apis = @rates['rates']
  end
  helper_method :apis

  def search
    if params[:search]
      @products = Product.find(:all, :conditions => ['search LIKE ?', "%#{params[:search]}%"])
    else
      @products = Product.all
    end

  end

  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    "/signedinuserprofile"
  end

  
  def search_params
    params.require(:product).permit(:Name, :Price, :Description, :Catagory)
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
    def index
        @order ||= Order.all
    end

    def create
        current_cart.observer(
            status: params[:status],
            first_name: params[:first_name],
            last_name: params[:last_name]
        )
        redirect_to orders_path
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

    def cart
        @order = current_cart.order
    end

    def create
        current_cart.add_item(
            product_id: params[:product_id],
            user_id: params[:user_id],
            quantity: params[:quantity]
        )
        redirect_to orders_path
    end

    def destroy 
        current_cart.remove_item(id: params[:id])
        redirect_to orders_path
    end

    def subtotal
        @subtotal = Order.where(status: nil).sum('quantity * price')
    end
    helper_method :subtotal
    
    
    def order_params
        params.permit(:first_name, :last_name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    
    def index
       @catagories = Product.find(10) 
       @sale = Product.find(4)
       @product = Product.find(1)
    end 

    def product
        @products = Product.all.paginate(page: params[:page], per_page: 5)
    end

    def product_detail
        @product = Product.find(params[:id])
        @user = current_user
    end

    def catagory
       @products = Product.where(:Catagory => "Electronics" )
    end

    def create
        @products = Product.new(params[:products])
        if @products.save
         redirect_to :action => 'product' 
        end
    end
    
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
    @profile.user_id = current_user.id

    respond_to do |format|
      format.html
      format.json {render json: @profile }
    end
    
  end


  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

    def signedinuserprofile
      profile = Profile.find_by_user_id(current_user.id) 
        if profile.nil?
            redirect_to "/profile/new"
        else
          @profile = Profile.find_by_user_id(current_user.id) 
          redirect_to "/profile/#{@profile.id}"
        end
    end
    

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :address)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
    #after_sign_in_path_for is called by devise
    def after_sign_in_path_for(user)
    "/signedinuserprofile" #here we provide
    #the path for the user's profile end
    end
end    

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/lrofiles_helper.rb
module LrofilesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/orders/cart.html.erb
<%= stylesheet_link_tag "cart" %>

<h1>Shopping Cart</h1>
<div class="container">
    <table class="rwd-table">
    <tr>
        <th>Order ID </th>
        <th>Price</th> 
        <th>Quantity</th>
        <th>Product ID</th>
        <th>User ID</th>
    </tr>
    <% @order.each do |o| %>
        <tr>
            <td><%= o.id %></td>
            <td><%= o.price %></td>
            <td><%= o.quantity %></td>
            <td><%= o.product_id %></td>
            <td><%= o.user_id %></td>
            <td>
                <%= form_for o, method: :delete do |f| %>
                    <%= f.submit "Remove", class:"btn1" %>
                <% end %>
            </td>

        </tr>
    <% end %>
        
    </table>

    <div class="check-out">
        <span class="">Subtotal(<%= current_cart.items_count %> items):</span> 
        <span class="total">€<%= subtotal %></span><br>


        <button class="btn2"><%= link_to "Check Out", checkout_path %></button>
    </div>
</div>

app/views/products/catagory.html.erb
<%= stylesheet_link_tag "products" %>

<% @products.each do |product| %>
       <div class="product">
       
                 <%= image_tag((product.Image_URL), :class => "card-img") %>
        

                <div class="product-info">
                    <%= content_tag( :h3, product.Name, :class => "heading") %><br>
                    
                    <%= truncate(product.Description, :length => 390, :escape => false) %><br>

                    <span class="margin"> Product I.D: <%= product.id %></span><br>
                    <span> Price: €<%= product.Price %></span><br>
                    <span>Catagory: <%= product.Catagory %></span><br>
                    <button class="btn"><%= link_to "More Details", product_path(product.id) %></button>
                </div>
                
            </div>
        <hr>
        
<% end %>

app/views/products/index.html.erb
<%= stylesheet_link_tag "index" %>

<body>
    <section>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <div class="container">
        <div class="card">
            <div class="card-bottom">
                <h3><b><%= link_to "Products:", products_path %></b></h3> 
                <%= image_tag((@product.Image_URL), :class => "card-img") %>
                <b><%= @product.Name %><br></b>
                <%= @product.Price %><br>
                <%= truncate(@product.Description, :length => 100, :escape => false) %> 
            </div>
        </div>

        <div class="card">
                <div class="card-bottom">
                <h3><b><%= link_to "On Sale!:", product_path(@sale.id)  %></b></h3>
                <%= image_tag((@sale.Image_URL), :class => "card-img") %>
                <b><%= @sale.Name %><br></b>
                <%= @sale.Price %><br>
                <%= truncate(@sale.Description, :length => 100, :escape => false) %> 
            </div>
        </div>

        <div class="card">
            <div class="card-bottom">
                <h3><b><%= link_to "Electronics & Accessories:", catagory_path %></b></h3> 
                <%= image_tag(("macbook.jpeg"), :class => "card-img") %>
                <b><%= @catagories.Name %><br></b>
                <%= @catagories.Price %><br>
                <%= truncate(@catagories.Description, :length => 100, :escape => false) %>
            </div>
        </div>
    </div>

<body>

app/views/products/product.html.erb
<%= stylesheet_link_tag "products" %>

<section>
    <% @products.each do |product| %>
       <div class="product">
       
                 <%= image_tag((product.Image_URL), :class => "card-img") %>
        

                <div class="product-info">
                    <%= content_tag( :h3, product.Name, :class => "heading") %><br>
                    
                    <%= truncate(product.Description, :length => 390, :escape => false) %><br>

                    <span class="margin"> Product I.D: <%= product.id %></span><br>
                    <span> Price: €<%= product.Price %></span><br>
                    <span>Catagory: <%= product.Catagory %></span><br>
                    <button class="btn"><%= link_to "More Details", product_path(product.id) %></button>
                </div>
                
            </div>
        <hr>
        
    <% end %>
    <%= will_paginate @products, :class => "padding" %>
<section>

app/views/products/product_detail.html.erb
<%= stylesheet_link_tag "product_detail" %>

<div class="product">
    <%= image_tag((@product.Image_URL), :class => "card-img") %>

    <div class="product-info">
        <h1 class="heading"><%= @product.Name %></h1>
        <span class="margin">Product I.D: <%= @product.id %></span><br>
        <span class="margin">Price: <%= @product.Price %></span><br>
        <span class="margin">Catagory: <%= @product.Catagory %></span><br>
        <span class="margin"><%= @product.Description %></span>
    </div>

</div>
<% if user_signed_in? %>
<div class="order-container">
    <span class="stock">In Stock</span>
    <%= form_tag orders_path %>
    <%= hidden_field_tag :product_id, @product.id %>
    <%= hidden_field_tag :user_id, @current_user.id %>
    <%= number_field_tag :quantity, 1, :class => "input"%>
    <%= submit_tag "Add To Cart", :class => "btn"%>
</div>
<% else %>
    <div class="order-container">
        <p>You must be signed in to place orders</p>
    </div>
<% end %>

app/views/profiles/_form.html.erb
<%= stylesheet_link_tag "checkout" %>
<div class="container">
    <div class="login-wrap">
    
    <div class="form">
      <%= form_with(model: profile, local: true) do |form| %>
        <% if profile.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(profile.errors.count, "error") %> prohibited this lrofile from being saved:</h2>

            <ul>
            <% profile.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :firstname %>
          <%= form.text_field :firstname, id: :profile_firstname %>
        </div>

        <div class="field">
          <%= form.label :lastname %>
          <%= form.text_field :lastname, id: :profile_lastname %>
        </div>

        <div class="field">
          <%= form.label :address %>
          <%= form.text_field :address, id: :profile_address %>
        </div>

        <div class="actions">
          <%= form.submit "Submit", :class => "button"  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.firstname %></td>
        <td><%= profile.lastname %></td>
        <td><%= profile.address %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @profile.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @profile.lastname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @profile.address %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>